# Generated by Django 3.2.9 on 2021-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brand', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(default=None, max_length=50)),
                ('Country', models.CharField(default=None, max_length=50)),
                ('prod_type', models.CharField(choices=[('V', 'Veg'), ('NV', 'Non-Veg')], max_length=2)),
                ('in_stock', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
