# Generated by Django 3.2.9 on 2021-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
